apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: cyclegan-trainer
  name: diag
spec:
  template:
    metadata:
      name: cyclegan-trainer
    spec:
      volumes:
      - name: libraries
        hostPath:
          path: /usr/lib/x86_64-linux-gnu
      - name: azurefile
        azureFile:
            secretName: azure-secret
            shareName: data
            readOnly: false      
      containers:
      - name: cyclegan-trainer
        command: ["/bin/sh", "-c"]
        args: ["sleep 100h"]
        image: wbuchwalter/cyclegan
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/lib/x86_64-linux-gnu_custom
          name: libraries
        - mountPath: "/data"
          name: azurefile       
      restartPolicy: Never
